{"name": "test_login[3]", "status": "broken", "statusDetails": {"message": "TypeError: 'SubRequest' object is not iterable", "trace": "request = <SubRequest 'pw_encryption' for <Function test_login[3]>>\n\n    @pytest.fixture(scope=\"function\")\n    def pw_encryption(request):\n        h1 = hashlib.md5()\n>       pw = list(request)\nE       TypeError: 'SubRequest' object is not iterable\n\nconftest.py:23: TypeError"}, "parameters": [{"name": "pw_encryption", "value": "'3'"}], "start": 1668157855824, "stop": 1668157855824, "uuid": "31ffef15-8f94-4ba6-b8d3-2e2f24655686", "historyId": "dfb013d80d4e1de44a816bb9825aa918", "testCaseId": "9a714c8af21ed863957756d3539d49e3", "fullName": "testcases.test_send_request.TestSendRequest#test_login", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_send_request"}, {"name": "subSuite", "value": "TestSendRequest"}, {"name": "host", "value": "PC-201703221222"}, {"name": "thread", "value": "15948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_send_request"}]}